server:
  port: 8081
  servlet:
    context-path: /v1.0/

spring:
  application:
    name: app-eventos-corporativos-api
    version: develop

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

azure:
  host:
    name: ${WEBSITE_SITE_NAME:localhost}
    slot: ${WEBSITE_SLOT_NAME:develop}

service:
---
server:
  port: ${PORT}
  servlet:
    context-path: /v1.0/
spring:
  profiles: release
  application:
    name: app-eventos-corporativos-api
    version: ${APP_VERSION}

  datasource:
    url: ${SQL_URL_CONECTION}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

azure:
  host:
    name: ${WEBSITE_SITE_NAME:localhost}
    slot: ${WEBSITE_SLOT_NAME:develop}

service:
